dist: trusty
sudo: required

language: python
python:
  - "2.7"

install:
  - export PATH=$PATH:./features/driver/linux
  - npm install -g bower
  - bower install
  - pip install -r requirements.txt
  - python manage.py migrate

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - sudo add-apt-repository ppa:ubuntu-mozilla-security/ppa -y
  - sudo apt-get update
  - sudo apt-get install firefox=54.0+build3-0ubuntu0.16.04.1
  - firefox -v

script: python manage.py behave
