dist: trusty
sudo: required

addons:
  firefox: 48
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - fluxbox >/dev/null 2>&1 &

language: python
python:
  - "2.7"
# command to install dependencies
install:
  - export PATH=$PATH:.
  - pip install -r requirements.txt
  - npm install -g bower
  - bower install
  - python manage.py migrate

# command to run tests
script: python manage.py behave
